irq0:
	push dword 0
	jmp irq_common

irq1:
	push dword 1
	jmp irq_common

irq2:
	push dword 2
	jmp irq_common

irq3:
	push dword 3
	jmp irq_common

irq4:
	push dword 4
	jmp irq_common

irq5:
	push dword 5
	jmp irq_common

irq6:
	push dword 6
	jmp irq_common

irq7:
	push dword 7
	jmp irq_common

irq8:
	push dword 8
	jmp irq_common

irq9:
	push dword 9
	jmp irq_common

irq10:
	push dword 10
	jmp irq_common

irq11:
	push dword 11
	jmp irq_common

irq12:
	push dword 12
	jmp irq_common

irq13:
	push dword 13
	jmp irq_common

irq14:
	push dword 14
	jmp irq_common

irq15:
	push dword 15
	jmp irq_common

